### ISSUE TITLE
pre-commit hook to run testthat's tests?

### ISSUE THREAD

**Issue by jucor** [lorenzwalthert/precommit#212]
Dear Lorenz
Thanks for this handy package!
Do you know if anyone has written a hook to run `devtools::test()`, by chance?
Thanks for any pointer.

**Comment by lorenzwalthert** [comment]
Hi. No, I am not aware of one. You could full-text search here: https://pre-commit.com/hooks.html

Also, I am not sure it's a good idea tbh. Because I think pre-commit hooks should run quickly, the rest can be deferred to CI/CD. There is a good (opinionated) blog post that discusses which changes should happen where: https://blog.r-hub.io/2020/04/29/maintenance/.
We won't add such a hook to this package because of the above reasons. If you really want this, you could write create your own repo to host hooks or write a local hook as documented [here](https://pre-commit.com/#repository-local-hooks). Something like
```
Rscript -e 'result <- testthat::test_package(); if (...) stop(...)'
```
could be used in a local hook with language `system` or similar. Just make it call `stop()` if there are failed tests, did not check the output of `testthat::test_package()`.
