### ISSUE TITLE
Release Scheduling

### ISSUE THREAD

**Issue by lorenzwalthert** [lorenzwalthert/precommit#365]
- [x] wait for {renv} 0.15 to be CRAN released to fix #342.
- [x] Wait for R 4.2 to appear in spring 2022.
- [x] update R image on pre-commi.ci to make sure [env variables are respected](https://github.com/rstudio/renv/issues/837) for multi-thread safety. Recommended packages to include: codetools for lintr.
- [x] auto-hook updates.
- [x] CRAN release.

**Comment by danielinteractive** [comment]
Thanks @lorenzwalthert first of all for this package, it is really useful!
One clarification question - is the current version compatible with R 4.2 or not yet?
I am asking because I have installed R 4.2 and now I am running into an error like this:
`namespace rlang 0.4.12 is already loaded, but >= 1.0.1 is required`
when setting up the pre-commit environment with renv etc. while I also get the warning
`Project requested R version '4.1.0' but '4.2.0' is currently being used`

**Comment by lorenzwalthert** [comment]
Which hook version are you running? Iirc this was fixed in a recent hook patch update. Try `pre-commit autoupdate` on the command line or `precommit::autoupdate()` in R. The warning on the R version can be ignored I think.

**Comment by danielinteractive** [comment]
Thanks @lorenzwalthert , I now upgraded to v0.2.2.9015 for `precommit` (and v2.6.2 for `prettier`) - and now it works! Thanks!

**Comment by lorenzwalthert** [comment]
Maybe we also need to catch these types of errors in all hooks and suggest updating the various components.
