### ISSUE TITLE
allow `hook_repo` to be an option

### ISSUE THREAD

**Issue by danhalligan** [lorenzwalthert/precommit#387]
`hook_repo` is currently hardcoded in `aaa.R`. This means that if a user defines an alternate repo/package containing hooks, then the setup of precommit will fail. Additionally, notes about available hooks will link to <https://github.com/lorenzwalthert/precommit> (rather than the custom package url).

For example, imagine using an alternate source that contains a link to a custom repo:
```
precommit::use_precommit(config_source = "my-pre-commit-config.yaml")
```

This will output something like the following and will then throw an error:

```
...
• Edit .precommit-hooks.yaml to (de)activate the hooks you want to use.
• All available hooks: https://pre-commit.com/hooks.html
• R specific hooks: https://github.com/lorenzwalthert/precommit
Error in config$repos[[idx]] : 
...
```

with traceback:

```
> traceback()
11: rev_read(".pre-commit-config.yaml")
10: is.factor(x)
9: grepl("https://github.com/lorenzwalthert/pre-commit-hooks", fixed = TRUE)
8: rev_read(".pre-commit-config.yaml") %>% grepl("https://github.com/lorenzwalthert/pre-commit-hooks", fixed = TRUE) %>% any()
7: upstream_repo_url_is_outdated()
6: assert_correct_upstream_repo_url()
5: force(code)
4: withr::with_dir(root, {
       assert_correct_upstream_repo_url()
    ...
3: autoupdate(root)
...
```

`rev_read` fails because it does not find the hardcoded hook_repo repository.

To get such functionality, we just need to add hook repo as a settable option I believe.

**Comment by lorenzwalthert** [comment]
Possibly yes. Can you describe your use case in more detail? Because I am not sure I fully understand what you want to achieve.

**Comment by lorenzwalthert** [comment]
This repo hosts hooks abut also more generic functionality to set up pre-commit from R

**Comment by danhalligan** [comment]
Yep no problem, I'll try and add a bit more flesh on the bones.

In our case, our whole R environment is dockerised, but I'd still like to run precommit hooks. Since R is not natively installed on the machine running git commands, this means we have to reimplement some of the git hooks in a separate package using docker: https://pre-commit.com/#docker.

**Comment by lorenzwalthert** [comment]
Thanks, and sorry for the delay. While it would not be a big deal to expose this option, I believe it would probably be better to just expose the hooks with `language: docker` here. Would that help you achieve your goal? Since the `entry point:` will be the same, maybe it's eveb sufficient to only provide a `Dockerfile` in that repo that has R installed and you could override `language: r` with `language: docker in your `.pre-commit-config.yaml` (pre-commit has the mechanism that you can [override configs](https://pre-commit.com/#pre-commit-configyaml---hooks) from the hook repo's `.pre-commit-hooks.yaml` in your `.pre-commit-config.yaml`). That way, we'd not even have to define a *docker version* of the hook.

ugh wait, seems like most configs can be overridden, but language not. Will file an issue upstream.

**Comment by danhalligan** [comment]
If I could make that work I think it would be preferable too, as I don't ideally want to redefine the R scripts. 
Let's hold and see if language can be overridden. 

If needed I can mock up a repo for testing purposes, just let me know.

**Comment by lorenzwalthert** [comment]
Submitted pre-commit/pre-commit#2294, you can upvote if you want 😄. Let's see what they say.

**Comment by lorenzwalthert** [comment]
Turns out that `language` can be overridden, but it's not encouraged, see https://github.com/pre-commit/pre-commit/issues/2294. Due to various complications, I am not really willing to support `language: docker` in my project. But I think you can do that yourself. I don't think you need to re-expose a lot of the functionality in the way you described:
```r
mypkg::use_precommit <- function(...) {
  precommit::use_precommit(
    config_source = system.file("extdata/pre-commit-config.yaml", package = "mypkg"),
    ...
)
```
I believe you can clone {precommit} into your container, `renv::restore()` all R dependencies and then `entry: Rscript 'path/to/precommit/inst/hooks/exported/style-files.R` in your `.pre-commit-config.yaml` and set `language: docker`. Or similar. 

In any case, I also looked into the error you got in more detail and I think we can just not perform that check if the repo `repo: https://github.com/lorenzwalthert/precommit` is not there, so this should not be a concern anyways. See #394.

**Comment by danhalligan** [comment]
Thanks for considering the change anyway. We've moved forward with reassigning the hardcoded `hooks_repo` using `assignInNamespace` which works for now albeit ugly.
