### ISSUE TITLE
Roxygenize hook only looks at MRAN; alternative CRAN repos are not specifiable

### ISSUE THREAD

**Issue by KyleDCox** [lorenzwalthert/precommit#472]
**Is your feature request related to a problem? Please describe.**
The `roxygenize` hook only downloads R packages from MRAN, and the user cannot specify other CRAN options. I'm using a private CRAN hosted in JFrog Artifactory, and I'm able to use it with `renv` to install custom packages hosted there. However, `precommit` (by default) only looks at MRAN.  

**Describe the solution you'd like**
An option for the `roxygenize` hook to use  a local `renv.lock` file instead of using the one at https://github.com/lorenzwalthert/precommit. The user's CRAN repo preferences are specified at the top of an renv.lock file.

**Describe alternatives you've considered**
Alternative solutions could be:
1. Creating a local hook which uses a local `renv.lock` (I'm too much of a novice to know if this is possible or how to do it)
2. Looking at the user's `options("repos")` to identify preferred CRAN repos

**Additional context**
Potentially related issues: #454 and #406  
I might be too much of a novice with precommit to understand what solutions are possible (e.g. using a custom local hook as described above).

**Comment by lorenzwalthert** [comment]
Hi @KyleDCox 

I think this problem applies to all hooks, not just the one for roxygenise. More generally, my experience with the roxygenise hook is that using pre-commits `language: r` is probably not a good idea since most developers have these dependencies locally anyways already, the specification in the `.pre-commit.yaml` file is complicated for the user and other reasons. So we could either rely on the project's renv, if any, or on the global R installation. We've done the latter for the latest hook added to this package, pkgdown. I think eventually we'll create a new roxygenise hook `roxygenise-local` or something similar to implement the pre-commit language switch away from `language: r`. 

Is the roxygenise hook of particular concern for you since you have private dependencies? First thing I'd then do is just comment it out on `.pre-commit-config.yaml` so you can still use pre-commit with your repo.
