### ISSUE TITLE
plan to release to CRAN?

### ISSUE THREAD

**Issue by maelle** [lorenzwalthert/precommit#49]
:wave: here, do you plan to release precommit to CRAN soon? Thanks. :-)

**Comment by lorenzwalthert** [comment]
Good idea :-) Yes I think I should do it before the end of the year. I must disable all tests that require python / conda though.

**Comment by lorenzwalthert** [comment]
@maelle if I put it on cran for you can you please do me a favour and quickly do a full ropensci review :smiley:. No honestly if there is anything missing or could be improved without great work, I am happy to hear your feedback.

**Comment by lorenzwalthert** [comment]
I might not able to hold the promise as macOS Catalina is giving us some problems due to changed default installation path that `reticulate` can't easily find (https://github.com/rstudio/reticulate/issues/661). I think we should wait until this is resolved in the next CRAN version. I don't want people to have a headache when they first use a package fresh brought to CRAN.

**Comment by lorenzwalthert** [comment]
@krzyslom Thanks for your contributions to {precommit}. I plan to submit this to CRAN soon, so I just wanted to ask you how many more issues you think you want to open before that? I value your contributions and want to make sure we don't miss something important for `v0.1.0`.

**Comment by lorenzwalthert** [comment]
Closed with https://twitter.com/i/timeline 🎉 .
