### ISSUE TITLE
Allow committing when `pre-commit.yml` is unstaged

### ISSUE THREAD

**Issue by pat-s** [lorenzwalthert/precommit#65]
Sometimes I have to turn off certain hooks for various reasons. This leads to a error stating that 

```
[ERROR] Your pre-commit configuration is unstaged.
```

which makes it impossible to commit anything. Can this be turned off? 
I neither want to change the hooks in general nor commit the changed YML file temporary.

**Comment by lorenzwalthert** [comment]
I think from a reproducibility point of view it does not make sense to commit anything if this file is also modified. I.e. if you  ran `pre-commit autoupdate`, you would use a hook version that would not reflect the hook version in your config or even you would (not) run hooks that people would think from looking at the config. That's why I believe this is not allowed. What prevents you from stashing the config file away for the time you want to commit? You could just add the files you want to commit to the index using `git add`, then `git stash --keep-index` to stash only non-staged files and proceed with your commit and afterwards `git stash pop`.

**Comment by pat-s** [comment]
> What prevents you from stashing the config file away for the time you want to commit? You could just add the files you want to commit to the index using git add, then git stash --keep-index to stash only non-staged files and proceed with your commit and afterwards git stash pop.

In this moment convenience and the fact that I do not "stash" so often in practice and have the workaround in my workflow. :/
In the end I temporarily called `precommit::uninstall_precommit()` to get going. I saw no other way easy way at this point (not thinking of the stashing approach) to get rid of the "commit lock".

> use a hook version that would not reflect the hook version in your config or even you would (not) run hooks that people would think from looking at the config.

I cannot assume the latter in practice since I cannot force anyone to install/use precommit even though the YAML exists in the repo.
As for (1) I would not expect users to update the precommit version of the YAML or even commit the change. 

Is this stage-lock a feature of upstream precommit or of the R package?

**Comment by lorenzwalthert** [comment]
> Is this stage-lock a feature of upstream precommit or of the R package?

Upstream. Also see the [FAQs](https://lorenzwalthert.github.io/precommit/articles/FAQ.html) on the functionality split.

So you have tried the two options to temporarily disable hooks?

https://pre-commit.com/#temporarily-disabling-hooks

**Comment by pat-s** [comment]
Thanks! Haven't yet consulted the doc of the upstream python package. Thanks for the pointers! I'll come back to them next time.

With this, I'll close here since there is no need anymore to temporarily change the YAML.
