### ISSUE TITLE
Prevent data leaks

### ISSUE THREAD

**Issue by dirkschumacher** [lorenzwalthert/precommit#90]
One potential precommit hook could be to warn if `.csv`, `.rds`, `.RData`, `.RHistory` etc. files are in the working directory or staged.

Use-case: someone works on a package and debugs using sensitive data that were written to disk during debugging and accidently commits them to git.

**Comment by lorenzwalthert** [comment]
I agree this would be useful. However, I am not sure it's R specific enough to fit into this repo. There are a host of other repos, in particular https://github.com/pre-commit/pre-commit-hooks, where this might fit better. It could be implemented in bash or python and non-R users could also benefit from it. 

The implementation could be very simple. The user can specify which files or file types are passed to a hook in the config as shown [here](https://github.com/pre-commit/pre-commit-hooks). If there are no files, the hook is not invoked anyways. Otherwise, the hook script could simply display the file names and fail informatively. Assuming the hook can be contributed to https://github.com/pre-commit/pre-commit-hooks, we could set the file argument in the template `.pre-commit-config.yaml` to match `.Rhistory`, `.RData`, `.rds` and `.csv`.

I am actually surprised that no one seemed to have implemented such a hook, I checked [here](https://pre-commit.com/hooks.html). Can you double check? 

For https://github.com/pre-commit/pre-commit-hooks, it looks as all hooks are in python. This is a helpful [example](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/check_case_conflict.py). Do you want to open an issue or PR there linking this issue?

**Comment by lorenzwalthert** [comment]
Actually I think you can simply use the fail language as described here: https://pre-commit.com/#fail and specify your file extensions of interest.

**Comment by lorenzwalthert** [comment]
We included the above (update) snippet in the template that will populate your root directory with `precommit::use_precommit()` by default.
