### ISSUE TITLE
Cannot exclude .RProfile from R pre-commit hooks

### ISSUE THREAD

**Issue by tblazina** [lorenzwalthert/precommit#91]
I'm having the problem of running these precommit hooks because we have a `.RProfile` file in the root folder of our project that contains:

```
setwd("/aktionstool")
```

When I run the precommit hooks (e.g. `style-files`) I get the following error:

```
Error in setwd("/aktionstool") : cannot change working directory
Execution halted
```

I have tried altering the `.pre-commit-config.yaml` file to exclude the `.Rprofile` file with

```
    -   id: style-files # Autoformat code syntax
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: .Rprofile
```

and variants of this using regex (e.g. `*.Rprofile`, `$Rprofile`, etc.) or but I unfortunately cannot get this file to be ignored. I'm not sure if this is a misunderstanding on my part with how the pre-commit library works or if it is specific to these hooks?

**Comment by lorenzwalthert** [comment]
I think rather the problem is that the hooks are invoked with `Rscript`, and not `Rscript --no-init-file`. We use shebang, for example here: https://github.com/lorenzwalthert/precommit/blob/master/inst/bin/style-files

For this reason, your `.Rprofile` is executed every time before the actual hook content. So it's unrelated to whether or not your `.Rprofile` is checked by any hook (it would be terrifying if the hook would try to run every file you want to commit!).

There are the following options IMHO:

- We run these hooks with the option `--no-init-file`, that is, I change the behaviour of all R pre-commit hooks in this repo. However, this would make it impossible for any hook to use a `.Rprofile` file. I'd rather not make this breaking API change since I believe there are use cases where one deliberately *wants* to run the `.Rprofile` before a commit.
- Check with the upstream repo if there is a way to detect if pre-commit is running, most likely via an environment variable. Then, in your `.Rprofile` file, check if that variable is set, if yes, don't run the problematic code.
- Last but not least, I am not sure why you ever would want to have `setwd()` in your `.Rprofile`, in particular with absolute paths like `/aktionstool`. I don't think it's good practice. Does this command run fine in the root of your repo? Because if yes, you should not have any problem here in the first place. Can you maybe put `stop(getwd())` in your `.Rprofile` and post here what is returned if you try to commit?
- Pragmatically, you could also wrap your `setwd()` into a `tryCatch()` to make things work.

**Comment by tblazina** [comment]
Thanks a l`ot for the quick response and explanation @lorenzwalthert. I hadn't thought of just using a `tryCatch()` as a workaround but this actually solves the issue.

Background for using the `setwd()` in the .Rprofile is that we are running it in a docker container which is being run on Kubernetes, I'm relatively new to the project (and to R) so i'm not entirely sure why the decision was made to put this here instead of simply setting the working directory in the `Dockerfile`. In any case this answers my question and solves the issue. Thanks again!
